[metadata]
name = netbox-ripe-sync
version = 1.0.0
description = NetBox plugin to synchronise inetnum/inet6num objects to the RIPE Database
long_description = file: README.md
long_description_content_type = text/markdown
license = Apache-2.0
classifiers =
    Programming Language :: Python :: 3
    Framework :: Django
    Topic :: Internet

[options]
packages = find:
python_requires = >=3.10
install_requires =
    requests>=2.28
    iso3166>=2.0

[options.packages.find]
include =
    netbox_ripe_sync
    netbox_ripe_sync.*

[options.extras_require]
s3 =
    boto3>=1.24

[options.package_data]
netbox_ripe_sync =
    templates/**/*.html
