[tox]
envlist = py310, py311, py312
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
    requests-mock
commands =
    pytest {posargs:tests/}

[testenv:lint]
deps =
    ruff
commands =
    ruff check netbox_ripe_sync/
